
#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project
HEADERS :=

# other places to look for files for this project
SEARCH  := src

# project-specific settings
TARGET ?= arduino_due

BMPTK := ../bmptk

# include the bmptk makefile.inc
include ../bmptk/Makefile.inc

